### ISSUE TITLE
Error when running Neoepiscope

### ISSUE THREAD

**Issue by leldershaw** [pdxgx/neoepiscope#15]
Error occurs after multiple warnings with message "Stop codon not detected prior to end of transcript {transcript_name}; this transcript may undergo degradation".

**Neoepiscope version: 0.4.1**

**Command used:**
neoepiscope call -b GRCh38 -c Mel5_tumor_v_Mel5_normal.haplotypes.prepped -v Mel5_tumor_v_Mel5_normal.merged.vcf -o Mel5_tumor_v_Mel5_normal.neoepiscope.out -k 9 -p netMHCpan 4 affinity,rank -a HLA-A*01:01,HLA-B*08:01,HLA-C*07:01 --nmd --pp --trv --igv --allow-nonstart --allow-nonstop

**Error message:**
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/neoepiscope", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/neoepiscope/__init__.py", line 696, in main
    neoepitopes, fasta = get_peptides_from_transcripts(
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/neoepiscope/transcript.py", line 3212, in get_peptides_from_transcripts
    peptides, protein = transcript_a.neopeptides(
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/neoepiscope/transcript.py", line 2277, in neopeptides
    read_frame1 = self.reading_frame(seq[3])
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/neoepiscope/transcript.py", line 876, in reading_frame
    if pos > self._start_codon or pos < self._stop_codon:
TypeError: '<' not supported between instances of 'int' and 'NoneType'

**Comment by maryawood** [comment]
Hi, thank you for pointing out this issue! We will be releasing a new version of neoepiscope soon, and I will address this issue in that release. I will let you know when that release is available!

**Comment by maryawood** [comment]
The new version of neoepiscope has been released! This version contains updates to the code to check whether the transcript has a stop codon prior to checking the stop codon position. Thanks again for pointing out this problem!
